[[plugins]]
repo = 'valloric/youcompleteme'
merged = 0
on_event = "VimEnter"
hook_add = '''
let g:ycm_use_clangd = 1
let g:ycm_show_diagnostics_ui = 1
let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'
let g:ycm_extra_conf_globlist = ['/Users/fujimotogen/Garage/bamboo/control/*',
                               \ '/Users/fujimotogen/Home/*']
let g:ycm_auto_hover='CursorHold'
let g:ycm_show_diagnostics_ui = 1
let g:ycm_error_symbol = ''
let g:ycm_warning_symbol = ''
augroup MyYCMCustom
  autocmd!
  autocmd FileType c,cpp let b:ycm_hover = {'command': 'GetDoc', 'syntax': &filetype}
augroup END
'''

[[plugins]] # コメントアウトとか手軽にできるようになる。
repo = "tpope/vim-commentary"
on_event = 'BufEnter'

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_event = "VimEnter"
hook_add = '''
let g:gitgutter_map_keys=0
let g:gitgutter_realtime = 1
"let g:gitgutter_eager = 0
'''

[[plugins]] # ファイルツリーの表示
repo = "preservim/nerdtree"
hook_add = '''
map <C-q> :NERDTreeToggle<CR>
let g:NERDTreeLimitedSyntax = 1
'''

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'mbbill/undotree'

[[plugins]] # 表組みをしてくれる。
repo ='godlygeek/tabular' # << https://devhints.io/tabular

[[plugins]]
repo = "chrisbra/csv.vim"
on_ft = 'csv'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # gitをvimから使う
repo ='tpope/vim-fugitive'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_add = '''
let g:vim_markdown_fenced_languages = ['c++=cpp', 'viml=vim', 'bash=sh', 'ini=dosini']
set conceallevel=1
'''
