[[plugins]]
repo = 'mbbill/undotree'

[[plugins]] # 表組みをしてくれる。
repo ='godlygeek/tabular' # << https://devhints.io/tabular

[[plugins]]
repo = "chrisbra/csv.vim"
on_ft = 'csv'

[[plugins]]
repo = 'junegunn/goyo.vim'
on_ft = ['txt', 'md']

[[plugins]]
repo = 'CoatiSoftware/vim-sourcetrail'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # gitをvimから使う
repo ='tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'guns/xterm-color-table.vim'
