############################################## Lazy_plugin ############################################
[[plugins]] # コメントアウトとか手軽にできるようになる。
repo = "tpope/vim-commentary"
on_event = 'BufEnter'

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_event = "VimEnter"
hook_add = '''
let g:gitgutter_map_keys=0
let g:gitgutter_realtime = 1
"let g:gitgutter_eager = 0
'''

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'mbbill/undotree'

[[plugins]] # 表組みをしてくれる。
repo ='godlygeek/tabular' # << https://devhints.io/tabular

[[plugins]]
repo = 'puremourning/vimspector'
marged = 0
hook_add = '''
let g:vimspector_enable_mappings = 'HUMAN'
'''

[[plugins]]
repo = 'wfxr/minimap.vim'
hook_add = '''
let g:minimap_highlight = 'CursorLine'
let g:minimap_width = 25
let g:minimap_highlight_range = 1
'''

############################################## FileType ############################################
[[plugins]]
repo = "chrisbra/csv.vim"
on_ft = 'csv'

[[plugins]]
repo = 'junegunn/goyo.vim'
on_ft = ['txt', 'md']

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = 'cpp'
hook_add = '''
let g:cpp_class_scope_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_class_decl_highlight = 1
let g:cpp_posix_standard = 1
let g:cpp_experimental_template_highlight = 1
let g:cpp_concepts_highlight = 1
let g:cpp_no_function_highlight = 1
'''

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'md', 'ipynb']
hook_add = '''
let g:vim_markdown_fenced_languages = ['c++=cpp', 'viml=vim', 'bash=sh', 'ini=dosini']
set conceallevel=1
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]]
repo = 'vim-latex/vim-latex'
merged = 0
on_ft = 'tex'
hook_add = '''
let g:Tex_SmartKeyBS = 0
let g:Tex_SmartKeyQuote = 0
let g:Tex_SmartKeyDot = 0
let g:Imap_UsePlaceHolders = 0
let g:Tex_CompileRule_pdf = 'lualatex $* > /dev/null'
let g:Tex_CompileRule_dvi = 'lualatex $* > /dev/null'
'''

