[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]] # ファイルツリーの表示
repo = "preservim/nerdtree"
hook_add = '''
map <C-q> :NERDTreeToggle<CR>
let g:NERDTreeLimitedSyntax = 1
'''

[[plugins]]
repo = "Xuyuanp/nerdtree-git-plugin"
hook_add = '''
let g:NERDTreeGitStatusIndicatorMapCustom = {
                \ 'Modified'  :'✹',
                \ 'Staged'    :'✚',
                \ 'Untracked' :'✭',
                \ 'Renamed'   :'➜',
                \ 'Unmerged'  :'═',
                \ 'Deleted'   :'✖',
                \ 'Dirty'     :'✗',
                \ 'Ignored'   :'☒',
                \ 'Clean'     :'✔︎',
                \ 'Unknown'   :'?',
                \ }
'''

[[plugins]] # Airlineのテーマ
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # ステータスラインの装飾
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline#extensions#default#layout = [[ 'a', 'b', 'c' ], [ 'x', 'y', 'z']]
let g:airline_detect_modified=1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter ='default'
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#denite#enabled = 1
let g:airline#extensions#fugitiveline#enabled = 1
let g:airline#extensions#bufferline#enabled = 1
let g:airline_section_y = airline#section#create_right(['neomake_custom','ffenc'])
let g:airline_stl_path_style = 'short'
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = '☰ '
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.dirty='⚡'
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = ''
let g:airline#extensions#tabline#right_sep = ' '
let g:airline#extensions#tabline#right_alt_sep = ''
let g:airline#extensions#tabline#buffer_idx_mode = 1
let g:airline#extensions#wordcount#enabled = 1
let g:airline_theme = 'murmur' " ubaryd,
set showtabline=2
set statusline=2                " ステータスラインの記述
set laststatus=2                " 下のステータスライン
set noshowmode                  " デフォルトのステータスラインを消す
'''

[[plugins]] # コメントアウトとか手軽にできるようになる。
repo = "tpope/vim-commentary"

[[plugins]]
repo = 'yggdroot/indentline'
hook_add =
'''
let g:indentLine_char = '┊'
" let g:indentLine_char = '|'
let g:indentLine_conceallevel=2
let g:indentLine_concealcursor=""
set conceallevel=1
set concealcursor-=incv
autocmd FileType tex let g:indentLine_enabled=0
'''

[[plugins]]
repo = 'valloric/youcompleteme'
merged = 0
hook_add = '''
let g:ycm_use_clangd = 1
let g:ycm_show_diagnostics_ui = 1
let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'
let g:ycm_extra_conf_globlist = ['/Users/fujimotogen/Garage/bamboo/control/*',
                               \ '/Users/fujimotogen/Labo/*']
let g:ycm_show_diagnostics_ui = 0
let g:ycm_error_symbol = ''
let g:ycm_warning_symbol = ''
nmap <leader>d <plug>(YCMHover)
augroup MyYCMCustom
  autocmd!
  autocmd FileType c,cpp let b:ycm_hover = {
    \ 'command': 'GetDoc',
    \ 'syntax': &filetype
    \ }
augroup END
'''

[[plugins]]
repo = 'honza/vim-snippets'
merged = 0

[[plugins]]
repo = 'SirVer/ultisnips'
merged = 0
hook_add = '''
let g:UltiSnipsExpandTrigger='<C-k>'
let g:UltiSnipsJumpForwardTrigger='<C-k>'
let g:UltiSnipsJumpBackwardTrigger='<C-l>'
'''

[[plugins]]
repo = 'puremourning/vimspector'
marged = 0
hook_add = '''
let g:vimspector_enable_mappings = 'HUMAN'
'''

[[plugins]]
repo = "rust-lang/rust.vim"
on_ft = "Rust"
hook_add = '''
'''

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
marged = 0
hook_add = '''
let g:cpp_class_scope_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_class_decl_highlight = 1
let g:cpp_posix_standard = 1
let g:cpp_experimental_template_highlight = 1
let g:cpp_concepts_highlight = 1
let g:cpp_no_function_highlight = 1
'''
